version: '3.8'

services:
  app_vet:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always