spring.datasource.url=jdbc:mariadb://dpg-cv0i9ai3esus73amd4lg-a:5432/clinica_vet_database
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.application.name=app_vet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
server.port=8080